name: Pipiline Test

on: push

jobs:
 test_api:
   name: API Tests - Robot
   runs-on: ubuntu-latest

   steps:
     - name: Checkout do repositório - API # run: echo Fazendo checkout do repositorio
       uses: actions/checkout@v4

     - name: Instalação e Configuração do Python - API # run: echo Instalação da versão 3.12 do Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.12'
    
     - name: Instalar Dependências do Projeto - API # run: echo Instalação das depedências do Projeto
       run: |
         pip install robotframework
         pip install robotframework-requests
         pip install robotframework-faker
         pip install robotframework-jsonlibrary
         pip install setuptools

    
     - name: Execução dos Testes de API com Robot # run: echo Executando os testes de API do Robot
       run: |
         robot --name "API and Web Tests" --outputdir results/ tests/api/

     - name: Resultados dos Testes - API # run: echo Salvando o Report dos Testes
       uses: actions/upload-artifact@v4
       if: always()
       with:
         name: resultado-testes-api
         path: results/

 test_web:
   name: Web Tests - Robot
   runs-on: ubuntu-latest

   steps:
    - name: Checkout do repositório - WEB # run: echo Fazendo checkout do repositorio
      uses: actions/checkout@v4

    - name: Instalação e Configuração do Python - WEB # run: echo Instalação da versão 3.12 do Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar Dependências do Projeto - WEB # run: echo Instalação das depedências do Projeto
      run: |
       pip install robotframework-seleniumlibrary

    - name:  Execução dos Testes WEB com Robot # run: echo Executando os testes de API do Robot
      run: |
       robot --name "API and Web Tests" --outputdir results/ tests/web/
  
    - name: Resultados dos Testes - WEB  # run: echo Salvando o Report dos Testes
      uses: actions/upload-artifact@v4
      if: always()
      with:
       name: resultado-testes-web
       path: results/

 merge:
    name: Merge Reports
    runs-on: ubuntu-latest
    needs: 
      - test_api
      - test_web

    steps:
      - name: Set up Python  # run: echo Instalação da versão 3.12 do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies  # run: echo Instalação das depedências do Projeto
        run: |
          pip install robotframework

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          path: results/

      - name: Merge Reports
        run: |
          rebot --merge results/robot-framework-report-api/output.xml results/robot-framework-report-web/output.xml
          ls -a

      - name: Upload Merge Report # run: echo Salvando o Report dos Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report
          path: ./*.html

 deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
      - merge
    permissions:
        contents: read
        pages: write
        id-token: write
    environment:
         name: github-pages
         url: https://jvluzc.github.io/RobotTestsAPI/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4  
        