name: Pipeline Test

on: push

jobs:
  test_api:
    name: API Tests - Robot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório - API
        uses: actions/checkout@v4

      - name: Instalação e Configuração do Python - API
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Dependências do Projeto - API
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-faker
          pip install robotframework-jsonlibrary
          pip install setuptools

      - name: Execução dos Testes de API com Robot
        run: |
          mkdir -p results
          robot --name "API Tests" --outputdir results/ --output results/output_api.xml tests/api/

      - name: Verificar arquivos gerados (API)
        run: ls -l results/

      - name: Resultados dos Testes - API
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report-api
          path: results/output_api.xml
